on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "LmeSzinc/AzurLaneAutoScript"
        source_branch: "master"
        destination_branch: "dashboard"
        github_token: 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
